"use client";
import Link from "next/link";
import { useI18n } from "@/components/locale-provider";
import { useFeatureResource } from "@/components/use-feature-resource";
import type { PublicJoinInfo } from "@/lib/club-administration-data";
export function ClubJoinSummary(){
  const {t,number}=useI18n(),{data,error}=useFeatureResource<PublicJoinInfo>("/api/join","settings");
  return <section className="rounded-xl border bg-card p-5 space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-xl font-semibold">{t("Join the club")}</h2>{data&&<p className={`text-sm ${data.recruitment_open?"text-emerald-500":"text-muted-foreground"}`}>{t(data.recruitment_open?"Applications open":"Applications closed")}</p>}</div>{data?<><dl className="space-y-2 text-sm"><div className="flex justify-between gap-3"><dt>{t("Application trophy requirement")}</dt><dd>{number(data.min_trophies)}</dd></div><div className="flex justify-between gap-3"><dt>{t("Minimum Power 11 brawlers")}</dt><dd>{number(data.min_power11)}</dd></div></dl><details className="text-sm"><summary className="cursor-pointer text-muted-foreground">{t("All club requirements")}</summary><dl className="mt-2 space-y-2">{data.min_ranked_points!=null&&<div className="flex justify-between gap-3"><dt>{t("Minimum ranked points")}</dt><dd>{number(data.min_ranked_points)}</dd></div>}{data.language&&<div><dt className="text-muted-foreground">{t("Language")}</dt><dd className="break-words">{data.language}</dd></div>}{data.availability&&<div><dt className="text-muted-foreground">{t("Preferred play times")}</dt><dd className="break-words">{data.availability}</dd></div>}</dl><p className="mt-2 text-xs text-muted-foreground">{t("Meeting the criteria does not guarantee admission.")}</p></details><Link href="/join" className="inline-flex min-h-9 items-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90">{t(data.recruitment_open?"Apply to join the club":"View club requirements")}</Link></>:<p className="text-sm text-muted-foreground">{t(error?"Applications are temporarily unavailable.":"Loading...")}</p>}</section>;
}
